name: Release And Publish Python Package

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  generate-release-body:
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Generate release body
        id: git-cliff
        uses: orhun/git-cliff-action@v4
        with:
          args: -vv --latest --strip all

  publish:
    runs-on: ubuntu-latest
    environment: release
    needs: [generate-release-body]
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Install the project
        run: uv sync
      - name: Build and publish
        run: |
          uv build
          uv publish --trusted-publishing automatic

  release:
    runs-on: ubuntu-latest
    needs: [generate-release-body, publish]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228  # v3
        with:
          body: ${{ needs.generate-release-body.outputs.release_body }}
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.GH_TOKEN }}
