name: Testing

on:
  pull_request:

  schedule:
    - cron: "0 6 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803  # v6
      - name: Install uv
        uses: astral-sh/setup-uv@94527f2e458b27549849d47d273a16bec83a01e9  # v7
        with:
          enable-cache: true
          python-version: "3.10"
      - name: Install the project
        run: uv sync --group testing
      - name: Run tests 3.10
        run: uv run --frozen pytest
